language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t huiqzhang619/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true huiqzhang619/docker-react npm run test
