language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t huiqzhang619/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true huiqzhang619/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "cn-northwest-1"
  app: "quan-docker"
  env: "QuanDocker-env"
  bucket_name: "elasticbeanstalk-cn-northwest-1-796401082536"
  bucket_path: "quan-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
